name: CI

on: [push]

jobs:
  docker-image:
    runs-on: ubuntu-latest

    env:
      app-directory: frontend
      back-directory: backend

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker FRONT image
        run: |
          cd ${{ env.app-directory }}
          docker build -t kotlin-app .

      - name: Build Docker BACK image
        run: |
          cd ${{ env.back-directory }}
          mvn clean package
          docker build -t spring-app .
  
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file backend/pom.xml
